default_language_version:
    python: python3.9
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: debug-statements
-   repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
    -   id: isort
-   repo: git@github.com:humitos/mirrors-autoflake.git
    rev: v1.3
    hooks:
    -   id: autoflake
        args: [
            '--expand-star-imports',
            '--ignore-init-module-imports',
            '--in-place',
            '--remove-all-unused-imports',
            '--remove-duplicate-keys',
            '--remove-unused-variable',
            '--recursive',
            '.'
        ]
-   repo: https://github.com/psf/black
    rev: 21.8b0
    hooks:
    -   id: black
-   repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        args: [--ignore=F401]

